name: TeachingExample
version: 1.0
description: abc
author: Chaoscrasher
main: com.jb1services.ta.main.TeachingExamplePlugin

commands:
  tbc:
    description: Allows you to various cool things!
    usage: use /tbc spawn [item] to spawn stuff!
